feat: retrieve catalog objects
Morel-Tech/square-connect-dart pull request #61
Opened 2022-11-20 22:36 UTC by BruceClark406

2022-11-20 23:35 UTC, mtwichel requested changes
Just a few nits 🙂

2022-11-20 23:35 UTC, mtwichel commented on lib/src/functions_model/batch_retrieve_catalog_objects.dart
> +  List<Object?> get props => [];
Add props?

2022-11-20 23:35 UTC, mtwichel commented on lib/src/functions_model/retrieve_catalog_objects.dart
> +class RetrieveCatalogObjectsResponse extends SquareResponse {
```suggestion
class RetrieveCatalogObjectResponse extends SquareResponse {
```
This is to retrieve one object right?

2022-11-20 23:38 UTC, mtwichel requested changes

2022-11-20 23:38 UTC, mtwichel commented on lib/src/functions_model/retrieve_catalog_objects.dart
> +  final List<CatalogObject> objects;
```suggestion
  final CatalogObject object;
```

2022-11-21 00:18 UTC, BruceClark406 commented on lib/src/functions_model/retrieve_catalog_objects.dart
> +class RetrieveCatalogObjectsResponse extends SquareResponse {
nice catch!

2022-11-21 00:19 UTC, BruceClark406 commented on lib/src/functions_model/batch_retrieve_catalog_objects.dart
> +  List<Object?> get props => [];
nice!

2022-11-21 00:25 UTC, merged